using System.Security.Cryptography;
using System.Text.Json;
using Certael.Server.Sessions;
using Npgsql;
using NpgsqlTypes;

namespace Certael.Coordinator;

public sealed record MatchLease(string TenantId,string GameId,string EnvironmentId,string MatchId,string OwnerRegion,string OwnerServer,long FencingEpoch,DateTimeOffset ExpiresAt);
public sealed class CoordinatorStore(NpgsqlDataSource dataSource, TimeProvider clock)
{
    public async ValueTask<bool> ReleaseAsync(MatchLease lease,string actor,CancellationToken ct)
    {await using var c=await dataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);const string sql="UPDATE certael_match_leases SET released_at=now() WHERE tenant_id=$1 AND game_id=$2 AND environment_id=$3 AND match_id=$4 AND owner_region=$5 AND owner_server=$6 AND fencing_epoch=$7 AND released_at IS NULL";await using var command=new NpgsqlCommand(sql,c,t);AddKey(command,lease.TenantId,lease.GameId,lease.EnvironmentId,lease.MatchId);command.Parameters.AddWithValue(lease.OwnerRegion);command.Parameters.AddWithValue(lease.OwnerServer);command.Parameters.AddWithValue(lease.FencingEpoch);if(await command.ExecuteNonQueryAsync(ct)!=1){await t.RollbackAsync(ct);return false;}await Audit(c,t,lease.TenantId,lease.MatchId,"LeaseReleased",actor,lease.FencingEpoch,new{lease.OwnerRegion,lease.OwnerServer},ct);await t.CommitAsync(ct);return true;}
    public async ValueTask<bool> IsCurrentOwnerAsync(MatchLease lease,CancellationToken ct)
    {await using var c=await dataSource.OpenConnectionAsync(ct);const string sql="SELECT 1 FROM certael_match_leases WHERE tenant_id=$1 AND game_id=$2 AND environment_id=$3 AND match_id=$4 AND owner_region=$5 AND owner_server=$6 AND fencing_epoch=$7 AND released_at IS NULL AND expires_at>now()";await using var command=new NpgsqlCommand(sql,c);AddKey(command,lease.TenantId,lease.GameId,lease.EnvironmentId,lease.MatchId);command.Parameters.AddWithValue(lease.OwnerRegion);command.Parameters.AddWithValue(lease.OwnerServer);command.Parameters.AddWithValue(lease.FencingEpoch);return await command.ExecuteScalarAsync(ct)is not null;}
    public async ValueTask<MatchLease?> AcquireAsync(string tenant,string game,string environment,string match,string region,string server,bool force,string actor,CancellationToken ct)
    {
        await using var connection=await dataSource.OpenConnectionAsync(ct); await using var transaction=await connection.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);
        const string select="SELECT owner_region,owner_server,fencing_epoch,expires_at,released_at FROM certael_match_leases WHERE tenant_id=$1 AND game_id=$2 AND environment_id=$3 AND match_id=$4 FOR UPDATE";
        await using var query=new NpgsqlCommand(select,connection,transaction); AddKey(query,tenant,game,environment,match); await using NpgsqlDataReader reader=await query.ExecuteReaderAsync(ct);
        string? oldRegion=null; long epoch=0; DateTimeOffset expires=DateTimeOffset.MinValue; bool released=false;
        if(await reader.ReadAsync(ct)){oldRegion=reader.GetString(0);epoch=reader.GetInt64(2);expires=reader.GetFieldValue<DateTimeOffset>(3);released=!reader.IsDBNull(4);} await reader.DisposeAsync();
        DateTimeOffset now=clock.GetUtcNow(); if(oldRegion is not null && !released && expires>now && !force && oldRegion!=region){await transaction.RollbackAsync(ct);return null;}
        long next=checked(epoch+1); DateTimeOffset nextExpiry=now.AddSeconds(30);
        const string upsert="INSERT INTO certael_match_leases VALUES($1,$2,$3,$4,$5,$6,$7,$8,NULL) ON CONFLICT(tenant_id,game_id,environment_id,match_id) DO UPDATE SET owner_region=$5,owner_server=$6,fencing_epoch=$7,expires_at=$8,released_at=NULL";
        await using(var command=new NpgsqlCommand(upsert,connection,transaction)){AddKey(command,tenant,game,environment,match);command.Parameters.AddWithValue(region);command.Parameters.AddWithValue(server);command.Parameters.AddWithValue(next);command.Parameters.AddWithValue(nextExpiry);await command.ExecuteNonQueryAsync(ct);}
        if(force)await Audit(connection,transaction,tenant,match,"ForcedFailover",actor,next,new{oldRegion,region},ct);
        await transaction.CommitAsync(ct); return new(tenant,game,environment,match,region,server,next,nextExpiry);
    }
    public async ValueTask<bool> RenewAsync(MatchLease lease,CancellationToken ct)
    { await using var c=await dataSource.OpenConnectionAsync(ct); const string sql="UPDATE certael_match_leases SET expires_at=$8 WHERE tenant_id=$1 AND game_id=$2 AND environment_id=$3 AND match_id=$4 AND owner_region=$5 AND owner_server=$6 AND fencing_epoch=$7 AND released_at IS NULL AND expires_at>now()"; await using var command=new NpgsqlCommand(sql,c);AddKey(command,lease.TenantId,lease.GameId,lease.EnvironmentId,lease.MatchId);command.Parameters.AddWithValue(lease.OwnerRegion);command.Parameters.AddWithValue(lease.OwnerServer);command.Parameters.AddWithValue(lease.FencingEpoch);command.Parameters.AddWithValue(clock.GetUtcNow().AddSeconds(30));return await command.ExecuteNonQueryAsync(ct)==1; }
    public async ValueTask RecordGrantAsync(RegionTransferGrantV1 grant,CancellationToken ct)
    { await using var c=await dataSource.OpenConnectionAsync(ct);const string sql="INSERT INTO certael_region_transfer_grants(grant_id,tenant_id,game_id,environment_id,match_id,player_subject,source_region,destination_region,fencing_epoch,nonce_digest,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)";await using var command=new NpgsqlCommand(sql,c);command.Parameters.AddWithValue(grant.GrantId);command.Parameters.AddWithValue(grant.TenantId);command.Parameters.AddWithValue(grant.GameId);command.Parameters.AddWithValue(grant.EnvironmentId);command.Parameters.AddWithValue(grant.MatchId);command.Parameters.AddWithValue(grant.PlayerSubject);command.Parameters.AddWithValue(grant.SourceRegion);command.Parameters.AddWithValue(grant.DestinationRegion);command.Parameters.AddWithValue(grant.LeaseEpoch);command.Parameters.AddWithValue(SHA256.HashData(grant.Nonce));command.Parameters.AddWithValue(grant.ExpiresAt);await command.ExecuteNonQueryAsync(ct);}
    public async ValueTask<bool> RedeemAsync(RegionTransferGrantV1 grant,string server,CancellationToken ct)
    {await using var c=await dataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);const string sql="UPDATE certael_region_transfer_grants SET redeemed_at=now(),redeemed_by=$2 WHERE grant_id=$1 AND redeemed_at IS NULL AND expires_at>now()";await using var command=new NpgsqlCommand(sql,c,t);command.Parameters.AddWithValue(grant.GrantId);command.Parameters.AddWithValue(server);if(await command.ExecuteNonQueryAsync(ct)!=1){await t.RollbackAsync(ct);return false;}const string fence="SELECT 1 FROM certael_match_leases WHERE tenant_id=$1 AND game_id=$2 AND environment_id=$3 AND match_id=$4 AND fencing_epoch=$5 AND (released_at IS NOT NULL OR expires_at<=now())";await using var check=new NpgsqlCommand(fence,c,t);AddKey(check,grant.TenantId,grant.GameId,grant.EnvironmentId,grant.MatchId);check.Parameters.AddWithValue(grant.LeaseEpoch);if(await check.ExecuteScalarAsync(ct)is null){await t.RollbackAsync(ct);return false;}await t.CommitAsync(ct);return true;}
    private static void AddKey(NpgsqlCommand c,string t,string g,string e,string m){c.Parameters.AddWithValue(t);c.Parameters.AddWithValue(g);c.Parameters.AddWithValue(e);c.Parameters.AddWithValue(m);}
    private static async ValueTask Audit(NpgsqlConnection c,NpgsqlTransaction t,string tenant,string match,string action,string actor,long epoch,object details,CancellationToken ct){await using var command=new NpgsqlCommand("INSERT INTO certael_coordinator_audit VALUES($1,$2,$3,$4,$5,$6,$7)",c,t);command.Parameters.AddWithValue(Guid.NewGuid());command.Parameters.AddWithValue(tenant);command.Parameters.AddWithValue(match);command.Parameters.AddWithValue(action);command.Parameters.AddWithValue(actor);command.Parameters.AddWithValue(epoch);command.Parameters.AddWithValue(NpgsqlDbType.Jsonb,JsonSerializer.Serialize(details));await command.ExecuteNonQueryAsync(ct);}
}
