using System.Text.Json;
using Certael.Server.Evidence;

namespace Certael.Server.Cases;

public sealed class InMemoryCaseStore(TimeProvider timeProvider) : ICaseStore
{
    private sealed class Entry(CaseSummary summary, byte[] key, DateTimeOffset deduplicateUntil)
    { public CaseSummary Summary=summary; public byte[] Key=key; public DateTimeOffset DeduplicateUntil=deduplicateUntil;
      public List<CaseEvidence> Evidence=[]; public List<CaseNote> Notes=[]; public List<CaseActivity> Activity=[]; public List<BoundedAction> Actions=[]; }
    private readonly object _gate=new(); private readonly Dictionary<Guid,Entry> _entries=[];
    public ValueTask<IReadOnlyList<CaseSummary>> SearchAsync(CaseQueueQuery query,CancellationToken ct)
    {ct.ThrowIfCancellationRequested();lock(_gate){return ValueTask.FromResult<IReadOnlyList<CaseSummary>>(_entries.Values.Select(e=>e.Summary).Where(c=>c.TenantId==query.TenantId&&c.EnvironmentId==query.EnvironmentId&&(query.State is null||c.State==query.State)&&(query.AssignedTo is null||c.AssignedTo==query.AssignedTo)&&(query.PlayerSubject is null||c.PlayerSubject==query.PlayerSubject)&&(query.Search is null||c.Title.Contains(query.Search,StringComparison.OrdinalIgnoreCase)||c.Summary.Contains(query.Search,StringComparison.OrdinalIgnoreCase))).OrderByDescending(c=>c.UpdatedAt).Take(Math.Clamp(query.Maximum,1,1000)).ToArray());}}
    public ValueTask<CaseDetail?> FindAsync(string tenantId,Guid caseId,CancellationToken ct)
    {ct.ThrowIfCancellationRequested();lock(_gate){if(!_entries.TryGetValue(caseId,out Entry? e)||e.Summary.TenantId!=tenantId)return ValueTask.FromResult<CaseDetail?>(null);return ValueTask.FromResult<CaseDetail?>(Detail(e));}}
    public ValueTask<CaseSummary?> OpenOrUpdateAsync(EvidenceBundle bundle,string title,string summary,string actor,TimeSpan window,CancellationToken ct)
    {ct.ThrowIfCancellationRequested();if(bundle.Verdict.Recommendation is VerdictRecommendation.Allow or VerdictRecommendation.Observe)return ValueTask.FromResult<CaseSummary?>(null);DateTimeOffset now=timeProvider.GetUtcNow();byte[] key=System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes($"{bundle.Verdict.TenantId}\0{bundle.Verdict.EnvironmentId}\0{bundle.Verdict.PlayerSubject}\0{bundle.SignedPolicyId}"));lock(_gate){Entry? e=_entries.Values.FirstOrDefault(x=>x.Summary.TenantId==bundle.Verdict.TenantId&&x.Key.SequenceEqual(key)&&x.DeduplicateUntil>now&&x.Summary.State is CaseState.Open or CaseState.InReview);if(e is null){Guid id=Guid.NewGuid();var value=new CaseSummary(id,bundle.Verdict.TenantId,bundle.Verdict.GameId,bundle.Verdict.EnvironmentId,bundle.Verdict.PlayerSubject,title,summary,CaseState.Open,bundle.SignedPolicyId,bundle.SignedPolicyVersion,null,1,now,now,null);e=new Entry(value,key,now+window);_entries[id]=e;}else e.Summary=e.Summary with{Summary=summary,Version=e.Summary.Version+1,UpdatedAt=now};foreach(Finding f in bundle.Findings.Where(f=>!e.Evidence.Any(x=>x.FindingId==f.FindingId)))e.Evidence.Add(new(bundle.Verdict.VerdictId,f.FindingId,f.RuleId,f.RuleVersion,f.SignalFamily,f.Trust,f.RiskContribution,f.Confidence,f.ObservedAt,bundle.ReplayDigest,JsonSerializer.Serialize(f.Fields)));e.Activity.Add(Activity(actor,"EvidenceAttached","signed policy threshold",new{bundle.Verdict.VerdictId},now));return ValueTask.FromResult<CaseSummary?>(e.Summary);}}
    public ValueTask<CaseSummary?> AssignAsync(string tenantId,Guid id,string? assigned,string actor,string reason,long version,CancellationToken ct)=>Mutate(tenantId,id,version,ct,(e,now)=>{e.Summary=e.Summary with{AssignedTo=assigned,Version=version+1,UpdatedAt=now};e.Activity.Add(Activity(actor,"AssignmentChanged",reason,new{assigned},now));return e.Summary;});
    public ValueTask<CaseNote?> AddNoteAsync(string tenantId,Guid id,string actor,string body,long version,CancellationToken ct)
    {CaseNote? note=null;Mutate(tenantId,id,version,ct,(e,now)=>{note=new(Guid.NewGuid(),actor,body,now);e.Notes.Add(note);e.Summary=e.Summary with{Version=version+1,UpdatedAt=now};e.Activity.Add(Activity(actor,"NoteAdded","operator note",new{note.NoteId},now));return e.Summary;});return ValueTask.FromResult(note);}
    public ValueTask<CaseSummary?> TransitionAsync(string tenantId,Guid id,CaseState target,CaseDisposition? disposition,string actor,string reason,long version,CancellationToken ct)=>Mutate(tenantId,id,version,ct,(e,now)=>{bool valid=(e.Summary.State,target) switch{(CaseState.Open,CaseState.InReview)=>true,(CaseState.InReview,CaseState.Resolved or CaseState.Dismissed)=>true,(CaseState.Resolved or CaseState.Dismissed,CaseState.Open)=>true,_=>false};if(!valid||target is CaseState.Resolved or CaseState.Dismissed&&disposition is null)return null;e.Summary=e.Summary with{State=target,Version=version+1,UpdatedAt=now,ResolvedAt=target is CaseState.Resolved or CaseState.Dismissed?now:null};e.Activity.Add(Activity(actor,"StateChanged",reason,new{target,disposition},now));return e.Summary;});
    public ValueTask<BoundedAction?> ApproveActionAsync(string tenantId,Guid id,BoundedActionKind kind,string targetType,string targetId,string reason,string requestedBy,string approvedBy,byte[] digest,long version,CancellationToken ct)
    {BoundedAction? action=null;if(digest.Length!=32||requestedBy==approvedBy)return ValueTask.FromResult<BoundedAction?>(null);Mutate(tenantId,id,version,ct,(e,now)=>{action=new(Guid.NewGuid(),kind,targetType,targetId,reason,requestedBy,approvedBy,"Approved",null,now,null);e.Actions.Add(action);e.Summary=e.Summary with{Version=version+1,UpdatedAt=now};e.Activity.Add(Activity(approvedBy,"BoundedActionApproved",reason,new{action.BoundedActionId,kind,targetType,targetId},now));return e.Summary;});return ValueTask.FromResult(action);}
    private ValueTask<CaseSummary?> Mutate(string tenant,Guid id,long version,CancellationToken ct,Func<Entry,DateTimeOffset,CaseSummary?> mutation){ct.ThrowIfCancellationRequested();lock(_gate){if(!_entries.TryGetValue(id,out Entry? e)||e.Summary.TenantId!=tenant||e.Summary.Version!=version)return ValueTask.FromResult<CaseSummary?>(null);return ValueTask.FromResult<CaseSummary?>(mutation(e,timeProvider.GetUtcNow()));}}
    private static CaseActivity Activity(string actor,string type,string reason,object details,DateTimeOffset now)=>new(Guid.NewGuid(),actor,type,reason,JsonSerializer.Serialize(details),now);
    private static CaseDetail Detail(Entry e)=>new(e.Summary,e.Evidence.ToArray(),e.Notes.ToArray(),e.Activity.ToArray(),e.Actions.ToArray());
}
