#!/usr/bin/env python
env = SConscript("godot-cpp/SConstruct")
env.Append(CPPPATH=["src", "../../runtime/certael-c-api/include"])
sources = Glob("src/*.cpp")
if env["platform"] == "windows":
    env.Append(LIBPATH=["../../target/x86_64-pc-windows-msvc/release"], LIBS=["certael_c_api"])
else:
    env.Append(LIBPATH=["../../target/release"], LIBS=["certael_c_api"])
library = env.SharedLibrary("addons/certael/bin/certael{}".format(env["suffix"]), source=sources)
Default(library)
