using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;
using NSec.Cryptography;

namespace Certael.Server.Actions;

public interface IActionProofVerifier
{
    bool Verify<TRequest>(AuthorizedAction<TRequest> action, ReadOnlySpan<byte> ephemeralPublicKey);
}

/// <summary>Verifies the proof generated by certael-core using identical canonical encoding.</summary>
public sealed class Ed25519ActionProofVerifier : IActionProofVerifier
{
    private static readonly byte[] Domain = "certael.action.v1\0"u8.ToArray();

    public bool Verify<TRequest>(AuthorizedAction<TRequest> action, ReadOnlySpan<byte> ephemeralPublicKey)
    {
        if (ephemeralPublicKey.Length != 32 || action.PossessionProof.Length != 64
            || action.PreviousDigest.Length != 32)
            return false;
        try
        {
            PublicKey key = PublicKey.Import(
                SignatureAlgorithm.Ed25519,
                ephemeralPublicKey,
                KeyBlobFormat.RawPublicKey);
            byte[] canonical = BinaryActionEnvelopeCodec.EncodeSigned(action);
            byte[] signed = new byte[Domain.Length + canonical.Length];
            Domain.CopyTo(signed, 0);
            canonical.CopyTo(signed, Domain.Length);
            return SignatureAlgorithm.Ed25519.Verify(key, signed, action.PossessionProof.Span);
        }
        catch (CryptographicException) { return false; }
        catch (ArgumentException) { return false; }
    }

    internal static byte[] Canonicalize<TRequest>(AuthorizedAction<TRequest> action) =>
        BinaryActionEnvelopeCodec.EncodeSigned(action);
}
