using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;
using NSec.Cryptography;

namespace Certael.Server.Actions;

public interface IActionProofVerifier
{
    bool Verify<TRequest>(AuthorizedAction<TRequest> action, ReadOnlySpan<byte> ephemeralPublicKey);
}

/// <summary>Verifies the proof generated by certael-core using identical canonical encoding.</summary>
public sealed class Ed25519ActionProofVerifier : IActionProofVerifier
{
    private static readonly byte[] Domain = "certael.action.v1\0"u8.ToArray();

    public bool Verify<TRequest>(AuthorizedAction<TRequest> action, ReadOnlySpan<byte> ephemeralPublicKey)
    {
        if (ephemeralPublicKey.Length != 32 || action.PossessionProof.Length != 64
            || action.PreviousDigest.Length != 32)
            return false;
        try
        {
            PublicKey key = PublicKey.Import(
                SignatureAlgorithm.Ed25519,
                ephemeralPublicKey,
                KeyBlobFormat.RawPublicKey);
            byte[] canonical = Canonicalize(action);
            byte[] signed = new byte[Domain.Length + canonical.Length];
            Domain.CopyTo(signed, 0);
            canonical.CopyTo(signed, Domain.Length);
            return SignatureAlgorithm.Ed25519.Verify(key, signed, action.PossessionProof.Span);
        }
        catch (CryptographicException) { return false; }
        catch (ArgumentException) { return false; }
    }

    internal static byte[] Canonicalize<TRequest>(AuthorizedAction<TRequest> action)
    {
        using var stream = new MemoryStream(160 + action.RawPayload.Length);
        WriteLengthPrefixed(stream, Encoding.UTF8.GetBytes(action.SessionId));
        WriteUInt64(stream, action.Sequence);
        Span<byte> guid = stackalloc byte[16];
        action.ActionId.TryWriteBytes(guid, bigEndian: true, out _);
        stream.Write(guid);
        WriteLengthPrefixed(stream, Encoding.UTF8.GetBytes(action.ActionType));
        WriteUInt32(stream, action.SchemaVersion);
        WriteInt64(stream, action.ClientMonotonicMicros);
        WriteLengthPrefixed(stream, action.RawPayload.Span);
        stream.Write(action.PreviousDigest.Span);
        return stream.ToArray();
    }

    private static void WriteLengthPrefixed(Stream stream, ReadOnlySpan<byte> bytes)
    {
        WriteUInt64(stream, checked((ulong)bytes.Length));
        stream.Write(bytes);
    }

    private static void WriteUInt64(Stream stream, ulong value)
    {
        Span<byte> buffer = stackalloc byte[8];
        BinaryPrimitives.WriteUInt64BigEndian(buffer, value);
        stream.Write(buffer);
    }

    private static void WriteInt64(Stream stream, long value)
    {
        Span<byte> buffer = stackalloc byte[8];
        BinaryPrimitives.WriteInt64BigEndian(buffer, value);
        stream.Write(buffer);
    }

    private static void WriteUInt32(Stream stream, uint value)
    {
        Span<byte> buffer = stackalloc byte[4];
        BinaryPrimitives.WriteUInt32BigEndian(buffer, value);
        stream.Write(buffer);
    }
}
